CREATE TABLE meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    price REAL NOT NULL,
    image TEXT
);

INSERT INTO meals (category, name, description, price, image) VALUES
('pasta', 'Truffle Tagliatelle', 'Fresh tagliatelle coated in black truffle cream with shaved parmesan.', 19.50, ''),
('pasta', 'Pistachio Pesto Linguine', 'Aromatic handmade pesto with roasted pistachios and burrata.', 18.90, ''),
('pasta', 'Lobster Ravioli', 'Ravioli stuffed with lobster, served in a light saffron cream.', 23.50, ''),
('pasta', 'Creamy Salmon Penne', 'Roasted salmon flakes in a velvety lemon cream sauce.', 17.80, ''),
('pasta', 'Carbonara Classica', 'Authentic Roman carbonara with guanciale and pecorino.', 16.90, ''),
('pasta', 'Mushroom Alfredo Fettuccine', 'Wild mushrooms sautéed in a parmesan-butter sauce.', 17.40, ''),
('pasta', 'Basil Pesto Gnocchi', 'Soft potato gnocchi tossed in fresh basil pesto.', 15.90, ''),
('pasta', 'Seafood Spaghetti', 'Calamari, mussels and prawns in white wine tomato sauce.', 21.30, ''),
('pasta', 'Four Cheese Tortellini', 'Creamy blend of parmesan, gorgonzola, pecorino and mozzarella.', 18.20, ''),
('pasta', 'Tomato Burrata Rigatoni', 'Slow roasted cherry tomatoes with burrata and basil.', 17.10, ''),
('pasta', 'Beef Ragu Pappardelle', 'Slow braised beef cooked in red wine and tomatoes.', 20.10, ''),
('pasta', 'Spinach Ricotta Cannelloni', 'Stuffed tubes baked in tomato & béchamel.', 16.50, ''),
('pasta', 'Garlic Chili Spaghetti', 'Light olive oil base with garlic, chili and herbs.', 13.20, ''),
('pasta', 'Tuscan Chicken Penne', 'Marinated chicken in a sun-dried tomato cream.', 18.80, ''),
('pasta', 'Porcini Risotto', 'Creamy risotto with porcini mushrooms and herbs.', 19.30, ''),
('pasta', 'Shrimp Scampi Linguine', 'Garlic butter prawns with lemon zest.', 21.60, ''),
('pasta', 'Pumpkin Sage Ravioli', 'Sweet pumpkin filling, sage butter drizzle.', 17.20, ''),
('pasta', 'Mediterranean Orzo', 'Olives, roasted peppers and feta.', 14.90, ''),
('pasta', 'Vodka Penne', 'Creamy tomato-vodka sauce with parmesan.', 15.80, ''),
('pasta', 'Bolognese Rigatoni', 'Slow-cooked beef and pork ragu.', 16.90, '');

INSERT INTO meals (category, name, description, price, image) VALUES
('burger', 'Wagyu Deluxe Burger', 'A5 wagyu patty with caramelized onions and truffle mayo.', 24.90, ''),
('burger', 'Classic Angus Cheeseburger', 'Melted cheddar, crisp pickles and house sauce.', 14.90, ''),
('burger', 'Smoky BBQ Bacon Burger', 'Smoked bacon, BBQ glaze and aged cheddar.', 16.40, ''),
('burger', 'Spicy Jalapeño Crunch', 'Jalapeños, pepper jack and crispy onions.', 15.80, ''),
('burger', 'Blue Cheese & Fig Burger', 'Creamy blue cheese with fig chutney.', 17.20, ''),
('burger', 'Double Smash Burger', 'Two thin patties, American cheese and garlic aioli.', 16.90, ''),
('burger', 'Chicken Crispy Deluxe', 'Buttermilk fried chicken with spicy honey.', 15.40, ''),
('burger', 'Portobello Veggie Burger', 'Grilled mushroom cap with pesto and mozzarella.', 14.20, ''),
('burger', 'Truffle Mushroom Burger', 'Sauteed mushrooms and truffle mayo.', 17.80, ''),
('burger', 'Mediterranean Lamb Burger', 'Seasoned lamb with tzatziki and fresh mint.', 18.50, ''),
('burger', 'Korean Bulgogi Burger', 'Sweet soy-marinated beef with kimchi.', 17.90, ''),
('burger', 'Swiss Alpine Burger', 'Swiss cheese, garlic mushrooms and cream sauce.', 16.70, ''),
('burger', 'Chipotle Chicken Burger', 'Grilled chicken with chipotle mayo.', 14.90, ''),
('burger', 'Avocado Ranch Burger', 'Ripe avocado, lettuce and ranch dressing.', 15.30, ''),
('burger', 'Bacon Maple Burger', 'Crispy bacon with maple glaze.', 15.70, ''),
('burger', 'Tex-Mex Burger', 'Corn salsa, smoked paprika and pepper jack.', 16.20, ''),
('burger', 'Italian Pesto Chicken Burger', 'Chicken breast with tomato and fresh pesto.', 15.40, ''),
('burger', 'Blackened Cajun Burger', 'Spicy blackened patty with lime mayo.', 16.10, ''),
('burger', 'Halloumi Veggie Stack', 'Grilled halloumi, tomato and basil.', 13.90, ''),
('burger', 'Chili Beef Melt', 'Beef patty topped with house chili.', 17.40, '');

INSERT INTO meals (category, name, description, price, image) VALUES
('steak', 'Ribeye 300g', 'Juicy marbled ribeye cooked to perfection.', 32.50, ''),
('steak', 'Filet Mignon 250g', 'Tender center-cut beef with herb butter.', 36.90, ''),
('steak', 'NY Strip 300g', 'Classic striploin with smoky seasoning.', 31.40, ''),
('steak', 'Peppercorn Sirloin', 'Crushed pepper sauce over grilled sirloin.', 29.80, ''),
('steak', 'Tomahawk Share Steak', 'Massive bone-in steak for two.', 69.90, ''),
('steak', 'Garlic Butter Rump', 'Grilled rump steak with garlic butter.', 24.80, ''),
('steak', 'BBQ Short Rib', 'Slow-cooked ribs glazed with smoky BBQ sauce.', 27.40, ''),
('steak', 'Flat Iron Steak', 'Lean, flavorful cut seasoned with herbs.', 22.90, ''),
('steak', 'Steak au Poivre', 'Creamy cognac pepper sauce.', 33.40, ''),
('steak', 'Chimichurri Steak', 'Argentina-style steak with herb sauce.', 30.20, ''),
('steak', 'Surf & Turf', 'Beef steak paired with grilled shrimp.', 39.90, ''),
('steak', 'T-Bone 350g', 'Tenderloin + strip in one cut.', 34.50, ''),
('steak', 'Korean Galbi Short Rib', 'Sweet-marinated Korean-style ribs.', 28.90, ''),
('steak', 'Prime Porterhouse', 'Large premium porterhouse steak.', 45.90, ''),
('steak', 'Smoked Brisket Plate', 'Slow-smoked brisket slices.', 22.50, ''),
('steak', 'Charcoal Skirt Steak', 'High-heat seared skirt with salsa verde.', 26.40, ''),
('steak', 'Bourbon Glazed Steak', 'Steak brushed with bourbon reduction.', 31.90, ''),
('steak', 'Rosemary Garlic Tenderloin', 'Tenderloin with herb crust.', 37.20, ''),
('steak', 'Miso Butter Steak', 'Umami-rich miso butter topping.', 33.60, ''),
('steak', 'Steak & Fries', 'Classic steak with crispy fries.', 24.90, '');

INSERT INTO meals (category, name, description, price, image) VALUES
('side', 'Truffle Parmesan Fries', 'Crispy fries tossed in truffle oil and parmesan.', 6.90, ''),
('side', 'Garlic Butter Bread', 'Toasted bread with fresh garlic butter.', 4.90, ''),
('side', 'Mixed Green Salad', 'Light salad with vinaigrette.', 5.40, ''),
('side', 'Mac & Cheese', 'Creamy cheese sauce baked golden.', 6.80, ''),
('side', 'Grilled Vegetables', 'Seasonal vegetables lightly charred.', 5.90, ''),
('side', 'Sweet Potato Fries', 'Crispy sweet potato wedges.', 5.80, ''),
('side', 'Coleslaw Deluxe', 'Crunchy slaw with creamy dressing.', 4.30, ''),
('side', 'Garlic Mashed Potatoes', 'Smooth buttery mashed potatoes.', 5.70, ''),
('side', 'Onion Rings', 'Large crispy battered rings.', 5.50, ''),
('side', 'Parmesan Broccoli', 'Roasted broccoli with parmesan flakes.', 5.60, ''),
('side', 'Cheesy Corn Bake', 'Oven-baked corn in a creamy cheese mix.', 6.10, ''),
('side', 'Caesar Side Salad', 'Romaine, parmesan, croutons.', 5.90, ''),
('side', 'Fried Mushrooms', 'Crispy coated button mushrooms.', 6.20, ''),
('side', 'Herb Rice', 'Fluffy rice with herbs.', 4.80, ''),
('side', 'Pesto Potatoes', 'Roasted potatoes tossed in pesto.', 5.50, ''),
('side', 'Mini Garlic Knots', 'Oven-baked knots with garlic butter.', 4.60, ''),
('side', 'Creamed Spinach', 'Velvety spinach in cream sauce.', 6.40, ''),
('side', 'Corn Ribs', 'Quartered corn glazed with chili butter.', 6.80, ''),
('side', 'Feta Tomato Salad', 'Diced tomato, cucumber and feta.', 5.70, ''),
('side', 'Crispy Polenta Bites', 'Crunchy bites with parmesan.', 6.10, ''),
('side', 'Twisted Fries', 'Crunchy fries with seasoning.', 3.10, ''),
('side', 'Crispy Fried Pork', 'Fried pork pieces.', 6.20, '');

INSERT INTO meals (category, name, description, price, image) VALUES
('drink', 'Fresh Orange Juice', 'Cold-pressed from ripe oranges.', 4.80, ''),
('drink', 'Coca-Cola', 'Chilled classic coke.', 3.20, ''),
('drink', 'Sparkling Water', 'Refreshing and bubbly.', 2.80, ''),
('drink', 'Still Mineral Water', 'Pure still water.', 2.60, ''),
('drink', 'Mango Smoothie', 'Blended mango with yogurt.', 5.40, ''),
('drink', 'Strawberry Milkshake', 'Creamy shake with real strawberries.', 5.90, ''),
('drink', 'Iced Latte', 'Cold coffee with milk.', 4.90, ''),
('drink', 'Hot Cappuccino', 'Espresso with steamed milk foam.', 4.20, ''),
('drink', 'Peach Iced Tea', 'Sweet iced tea with peach flavor.', 3.80, ''),
('drink', 'Lemon Iced Tea', 'Refreshing lemon iced tea.', 3.60, ''),
('drink', 'Virgin Mojito', 'Mint, lime and soda.', 5.20, ''),
('drink', 'Berry Lemonade', 'Fresh berries with lemonade.', 4.60, ''),
('drink', 'Energy Drink', 'Sparkling energy boost.', 3.40, ''),
('drink', 'Ginger Beer', 'Non-alcoholic spicy ginger soda.', 3.90, ''),
('drink', 'Chocolate Milkshake', 'Rich cocoa shake.', 5.60, ''),
('drink', 'Matcha Latte', 'Creamy matcha with milk.', 4.80, ''),
('drink', 'Banana Smoothie', 'Fresh banana with yogurt.', 5.10, ''),
('drink', 'Caramel Iced Coffee', 'Sweet caramel cold brew.', 5.30, ''),
('drink', 'Fresh Apple Juice', 'Cold-pressed apple juice.', 4.70, ''),
('drink', 'Watermelon Cooler', 'Light, refreshing watermelon drink.', 4.90, '');
